# Copyright Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: dlstreamer-pipeline-server-config-input
data:
  config.json: |-
    {{- $path := printf "apps/%s/pipeline-server-config.json" .Values.env.SAMPLE_APP }}
    {{- $json := .Files.Get $path }}
    {{- $json | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: otel-config
data:
  otel-collector-config.yaml: |-
{{ .Files.Get "otel-collector-config.yaml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s  # Scrape metrics every 10 seconds

    scrape_configs:
      - job_name: 'otel-log-collector'
        static_configs:
          - targets: ['{{ .Values.env.HOST_IP }}:{{ $.Values.config.otel_collector.ext.otlp_prometheus_endpoint_port }}']