# Copyright Intel Corporation

namespace:
DOCKER_REGISTRY: ''
DOCKER_USERNAME: ''
DOCKER_PASSWORD: ''
imagePullPolicy: Always
storageClassName: manual
mqtt_broker:
  image: eclipse-mosquitto
  imageTag: 2.0.21
coturn:
  image: coturn/coturn
  imageTag: 4.7
mediamtx:
  image: bluenviron/mediamtx
  imageTag: 1.11.3
dlstreamer_pipeline_server:
  image: intel/edge-ai-dlstreamer-pipeline-server
  imageTag: 20250731_EAL1.2_DLSPS_RC4-ubuntu24
grafana:
  image: grafana/grafana
  imageTag: 11.5.4
node_red:
  image: nodered/node-red
  imageTag: 3.1
env:
  ENABLE_WEBRTC: "true"
  ENABLE_RTSP: "true"
  HOST_IP: <HOST_IP>
  ENABLE_HTTPS_MODE: false
  MIN_LOG_LEVEL: DEBUG
  http_proxy:
  https_proxy:
  no_proxy:
privileged_access_required: false
gpu:
  enabled: false
  type: "gpu.intel.com/i915"
  count: 1
webrtcturnserver:
  username: <WEBRTC_TURN_SERVER_USERNAME>
  password: <WEBRTC_TURN_SERVER_PASSWORD>
config:
  mediamtx:
    name: mediamtx
    int:
      mediamtx_port: "8889"
      mediamtx_sdp_port: "8189"
      mediamtx_api_port: "9997"
    ext:
      mediamtx_port: "30489"
      mediamtx_sdp_port: "30488"
      mediamtx_api_port: "30487"
  coturn:
    name: coturn
    int:
      coturn_tcp_port: "3478"
      coturn_udp_port: "3478"
    ext:
      coturn_tcp_port: "30486"
      coturn_udp_port: "30486"
  dlstreamer_pipeline_server:
    name: dlstreamer-pipeline-server
    int:
      rest_api_port: "8080"
      rtsp_output_port: "8554"
    ext:
      rest_api_port: "30485"
      rtsp_output_port: "30484"
  mqtt_broker:
    name: mqtt-broker
    int:
      mqtt_port: "1883"
    ext:
      mqtt_port: "30483"
  grafana:
    name: grafana
    int:
      web_ui_port: "3000"
    ext:
      web_ui_port: "30480"
  node_red:
    name: node-red
    int:
      web_ui_port: "1880"
    ext:
      web_ui_port: "30482"
volumes:
  pipelines:
    name: vol-pipelines
    size: 100Mi
    location: "/home/pipeline-server/pipelines"
    hostpath: "/opt/intel/eii/pipelines"
